import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import "../styles/icomoon.css"

const SairaFont = Saira({
  variable: "--Saira",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen relative font1 antialiased bg-gradient-to-br from-slate-800 via-cyan-950 to-slate-900`}
      >
        {children}
      </body>
    </html>
  );
}
